// <auto-generated />
namespace MVCPrj1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class testa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testa));
        
        string IMigrationMetadata.Id
        {
            get { return "201510060229028_testa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
