// <auto-generated />
namespace MVCPrj1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class up_identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up_identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201602141344374_up_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
